### ISSUE TITLE
How to generate the '.pkl' files from the source dataset?

### ISSUE THREAD

**Issue by Yankeegsj** [kami93/CMU-DATF#1]
After I download the argoverse and  nuscence dataset, I still cant run the code.  I found all samples are saved in '.pkl' files in the code, but there are no these files in the source dataset. 
So, how can I get these files that can be  used in the code from the source argoverse motion forecasting dataset  and nuscence  dataset?

**Comment by TsuTikgiau** [comment]
Same issues here. Can you tell us how to prepare the datasets correctly?

**Comment by mzahran001** [comment]
Hi @kami93 
I have the same issues here. 
Can you tell us how to prepare the datasets correctly?

**Comment by os1a** [comment]
Same here,

would be nice if you can provide the script to process the raw data or the processed dataset (in .pkl files).

Under dataset/argoverse.py: the function extract_directory looks for reference frames in a folder named observations where these reference frames are provided as .pkl files.

**Comment by kami93** [comment]
Hello @Yankeegsj @TsuTikgiau @os1a,

Thank you for your interest in our model and your patience. As you might have noticed, our model uses a preprocessed version of datasets based on the vanilla NuScenes and Argoverse. Though we will soon release codes for data processing, I can send you the pkls in person, upon your requests through email.

Please let me know. Thank you again!

**Comment by TsuTikgiau** [comment]
Hello @kami93, thank you for your reply! My email address is tsu.tikgiau@gmail.com .  Thanks for your help!

**Comment by os1a** [comment]
Hi @kami93 , Thanks, my email address is os1a@hotmail.com

**Comment by Yankeegsj** [comment]
Thanks   @kami93 ,my email is  jjd77642@163.com

**Comment by intelpro** [comment]
Hi @kami93 , my email address is intelpro@kaist.ac.kr

**Comment by kami93** [comment]
Hi everyone!
The files are being uploaded and will be available in 6 hrs (estimated). We will send you the links as soon as they are online.
Thanks for your patience!

**Comment by kami93** [comment]
Hi everyone! @intelpro @Yankeegsj @os1a @TsuTikgiau 
The files are being uploaded and will be available in 6 hrs (estimated). We will send you the links as soon as they are online.
Thanks for your patience!

**Comment by TsuTikgiau** [comment]
Thank you! @kami93 
I notice that in addition to the pkl files for trajectories, the pkl files for processed maps are also missing. Are these files also included?

**Comment by xuerlee** [comment]
Hi @kami93 
same issues here, 
could please you send me the pkls? My email is xuer0324@sina.com
Thanks for your help!

**Comment by xuerlee** [comment]
Hi @kami93
same issues here,
could you please send me the pkls? My email is xuer0324@sina.com
Thanks for your help!

**Comment by Redaimao** [comment]
Hi @kami93 ,
Thanks for your wonderful work.
Same issue here, so could you please send those pkls or shared links via my email redaimao.bao@gmail.com
Many thanks!

**Comment by layssi** [comment]
@kami93 ,
This is great work. 
Do you have a time frame as to when the data processing codes for argoverse would be released?
Also please send me a link to the pkls @ layssi at yahoo.com
Thank you

**Comment by chen84jianxiao** [comment]
Hi @kami93 
Thanks for your work.
could you please send me links to those pkls, my email address is jianxiaochen84@gmail.com.

**Comment by JasonMa2016** [comment]
@kami93 
Thank you for open sourcing your code! Could you also please send me the links to the pkls files? My email address is yechengma@gmail.com 

Best wishes!

**Comment by pmlakner** [comment]
Can someone also send me the links? My email is lakner.pm@gmail.com

**Comment by guoyage** [comment]
@kami93
Thank you for open sourcing your code! Could you also please send me the links to the pkls files? My email address is 13664109089@163.com

Best wishes!

**Comment by Manojbhat09** [comment]
Please take a look at the latest commit @guoyage. Thanks
