### ISSUE TITLE
Question about drivable area in Argoverse dataset

### ISSUE THREAD

**Issue by leoncesc** [kami93/CMU-DATF#2]
Thanks for sharing your great work.
I have some questions about the description of the drivable area in the paper. 

1. what is the distance transform of the binary mask? Is the binary mask the binary drivable area matrix?

2. How can I calculate the distance between one predicted location and drivable area?

**Comment by kami93** [comment]
Hi, @leoncesc.

Here's a good reference for the distance transform. https://en.wikipedia.org/wiki/Distance_transform. There are many practical implementations of it, e.g., scipy.ndimage.distance_transform*.
