### ISSUE TITLE
Multi-gpu Training

### ISSUE THREAD

**Issue by os1a** [kami93/CMU-DATF#5]
Hi,

Thanks for the nice work, I have a question regarding the multi-gpu training.
According to the training arguments, you specify --gpu_devices 3. But I could not find in the code the place for setting the model to be trained on multi-gpu.

**Comment by kami93** [comment]
Hi,

The naming for that argument could be confusing. "gpu_devices" indicates the gpu index, not # of gpus for training.

**Comment by os1a** [comment]
OK, thanks for your answer.
